apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: default
spec:
  selector:
    app:  mongodb
  type: ClusterIP
  ports:
  - name: mongodb-svc
    protocol: TCP
    port: 27017
    targetPort: 27017