apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
  namespace: default
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
  - name: mongo-express-svc
    protocol: TCP
    port: 8081
    targetPort: 8081
                          