apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongo-express
  namespace: default
  labels:
    app:  mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  mongo-express
    spec:
      containers:
      - name:  mongo-express
        image:  mongo-express:0.54.0
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
             secretKeyRef:
              name: mysecret
              key: mongo_username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
             secretKeyRef:
              name: mysecret
              key: mongo_password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
             configMapKeyRef: 
              name: mongo-config
              key: database_host
        ports:
        - containerPort: 8081
          name:  mongo-express      